# -*- coding: utf-8 -*-
'''
nbpkg defspec
'''

NBPKG_MAGIC_NUMBER = b'\x1f\x8b'
NBPKG_HEADER_MAGIC_NUMBER = '\037\213'

NBPKGINFO_MIN_NUMBER = 1000
NBPKGINFO_MAX_NUMBER = 1146

# data types definition
NBPKG_DATA_TYPE_NULL = 0
NBPKG_DATA_TYPE_CHAR = 1
NBPKG_DATA_TYPE_INT8 = 2
NBPKG_DATA_TYPE_INT16 = 3
NBPKG_DATA_TYPE_INT32 = 4
NBPKG_DATA_TYPE_INT64 = 5
NBPKG_DATA_TYPE_STRING = 6
NBPKG_DATA_TYPE_BIN = 7
NBPKG_DATA_TYPE_STRING_ARRAY = 8
NBPKG_DATA_TYPE_I18NSTRING_TYPE = 9

NBPKG_DATA_TYPES = (NBPKG_DATA_TYPE_NULL,
                  NBPKG_DATA_TYPE_CHAR,
                  NBPKG_DATA_TYPE_INT8,
                  NBPKG_DATA_TYPE_INT16,
                  NBPKG_DATA_TYPE_INT32,
                  NBPKG_DATA_TYPE_INT64,
                  NBPKG_DATA_TYPE_STRING,
                  NBPKG_DATA_TYPE_BIN,
                  NBPKG_DATA_TYPE_STRING_ARRAY,)

NBPKGINFO_DISTNAME = 1000
NBPKGINFO_PKGNAME = 1000
NBPKGINFO_CATEGORY = 1000
NBPKGINFO_MAINTAINER = 1000
NBPKGINFO_HOMEPAGE = 1020
NBPKGINFO_COMMENT = 1000
NBPKGINFO_LICENSE = 1000
NBPKGINFO_VERSION = 1001
NBPKGINFO_RELEASE = 1002
NBPKGINFO_DESCRIPTION = 1005
NBPKGINFO_LONG_DESCRIPTION = 1005
NBPKGINFO_OS_VERSION = 1000
NBPKGINFO_COPYRIGHT = 1014
NBPKGINFO_SIZE_PKG = 1000
NBPKGINFO_MACHINE_ARCH = 1022


NBPKGINFOS = (
           NBPKGINFO_DISTNAME,
           NBPKGINFO_PKGNAME,
           NBPKGINFO_CATEGORY,
           NBPKGINFO_MAINTAINER,
           NBPKGINFO_HOMEPAGE,
           NBPKGINFO_COMMENT,
           NBPKGINFO_LICENSE,
           NBPKGINFO_VERSION,
           NBPKGINFO_RELEASE,
           NBPKGINFO_LONG_DESCRIPTION,
           NBPKGINFO_OS_VERSION,
           NBPKGINFO_SIZE_PKG,
           NBPKGINFO_MACHINE_ARCH,
)

NBPKG_HEADER_BASIC_FILES = dict()

NBPKG_HEADER_BASIC_FILES = {
  'NBPKG_BUILD_INFO':'+BUILD_INFO',
  'NBPKG_BUILD_VERSION':'+BUILD_VERSION',
  'NBPKG_COMMENT':'+COMMENT',
  'NBPKG_CONTENTS':'+CONTENTS',
  'NBPKG_DESC':'+DESC',
  'NBPKG_SIZE_ALL':'+SIZE_ALL',
  'NBPKG_SIZE_PKG':'+SIZE_PKG',
}
